include:
  - board: bmp_boost
    shield: tecla_cero_left
    snippet: "studio-rpc-usb-uart split-central input-split-listener"
    artifact-name: tecla_cero_left_central
  - board: bmp_boost
    shield: tecla_cero_right
    snippet: "studio-rpc-usb-uart input-trackball input-split"
    artifact-name: tecla_cero_right_peripheral
  - board: bmp_boost
    shield: tecla_cero_left
    snippet: studio-rpc-usb-uart
    artifact-name: tecla_cero_left_peripheral
  - board: bmp_boost
    shield: tecla_cero_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener"
    artifact-name: tecla_cero_right_central
  - board: bmp_boost
    shield: settings_reset
